module.exports = class GraphType {
    static SYSTEM_PERMISSION_LIST = 'SYSTEM_PERMISSION_LIST';

    static SYSTEM_FRIEND_LIST = 'SYSTEM_FRIEND_LIST';

    static SYSTEM_OBJECT_NEST = 'SYSTEM_OBJECT_NEST';
}
