input Friend {
    id: Int! = 0
    enabled: Boolean! = true
    roleName: String = "user"
    resourceName: String
    parentResource: String
    water: Float = 1.5
}
input SYSTEM_FRIEND_LIST {
    data: [Permission]!
    code: String
}